### ISSUE TITLE
Set english as default target language

### ISSUE THREAD

**Issue by Kalitsune** [Kalitsune/open-discord-translator#31]
Pretty explicit, you just need to change the commands specs so that the default value for 'to' is 'en'.

**Comment by trottiemcqueen** [comment]
Hello is this issue still avail?

**Comment by Kalitsune** [comment]
Hello! Yes it is!

The target argument for the commands:
- replicas add
- translate
- send
Needs to be set to `required(false)`.

And the translation drivers in `/translations/drivers/*` needs to have their `to` argument in their translate functions be attributed to `en` as their default value.

The exemple at the end of the README should also be updated.

Sorry for the delay and thank you for your time!

**Comment by trottiemcqueen** [comment]
Great afternoon. Do you have the link so I register for a token?

**Comment by Kalitsune** [comment]
Hello! You can create a discord token for you bot by following this tutorial: https://discordjs.guide/preparations/setting-up-a-bot-application.html#creating-your-bot

Once you've created your bot you just have set your token in the .env.dev file and you'll be good to go! 

If you're unsure about how to do it you can also check the dev part in the readme!

Once you've set the token, you can start the bot and it will automatically generate an invite link in the console. Use that to invite the bot in your server!

**Comment by trottiemcqueen** [comment]
Oh ok I see it *sigh it was right in front of me. As for the english
default, I will admit if I'm having difficulty with something - will I be
making this change in the translations folder? I don't
see anywhere else that would possibly need a change.

**Comment by Kalitsune** [comment]
In the example  found in the README at the [add-a-new-translation-api-driver](https://github.com/Kalitsune/open-discord-translator#add-a-new-translation-api-driver) section, find the translate function and update it as follows:

```js
// Before
async translate(text, to,  from = undefined) { ... };

// After
async translate(text, to = 'en', from = undefined) { ... };
```

This change ensures that the to parameter defaults to 'en' if not explicitly provided.

Additionally, make sure to update the driver files in the /translations/drivers/ directory. In each driver file, adjust the translation call as follows:

```js
// Before
async translate(text, to,  from = undefined) { ... };

// After
async translate(text, to = 'en', from = undefined) { ... };
```
This modification handles the case where the user doesn't specify an explicit target language (because it is now optional).

**Comment by trottiemcqueen** [comment]
Thank you for the insight. I really appreciate it and now have a better understanding.

**Comment by trottiemcqueen** [comment]
Sign me up, if there are any projects you and your team are working on.
